// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL-eMrhfOdshGf15kM4Y_wvD5OvLjWYU4',
    appId: '1:225920306772:web:4720f66875d9b235b667c1',
    messagingSenderId: '225920306772',
    projectId: 'sistema-login-cadastro-c66b3',
    authDomain: 'sistema-login-cadastro-c66b3.firebaseapp.com',
    storageBucket: 'sistema-login-cadastro-c66b3.firebasestorage.app',
    measurementId: 'G-6YQHRMM911',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQLwrImG3kin1ZA5yXId0dI3kpnIqhvM',
    appId: '1:225920306772:android:dfc36a9793df71e6b667c1',
    messagingSenderId: '225920306772',
    projectId: 'sistema-login-cadastro-c66b3',
    storageBucket: 'sistema-login-cadastro-c66b3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL-eMrhfOdshGf15kM4Y_wvD5OvLjWYU4',
    appId: '1:225920306772:web:24eccf974970bf55b667c1',
    messagingSenderId: '225920306772',
    projectId: 'sistema-login-cadastro-c66b3',
    authDomain: 'sistema-login-cadastro-c66b3.firebaseapp.com',
    storageBucket: 'sistema-login-cadastro-c66b3.firebasestorage.app',
    measurementId: 'G-YB7J4MYEK2',
  );
}
